# 网站基本信息
title: Awesome Sites
description: 精心收集的实用网站合集，涵盖开发工具、学习资源、实用服务等各个领域
url: https://yourusername.github.io
baseurl: /awesome-sites
author: Your Name
email: your-email@example.com

# GitHub Pages 设置
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# SEO 优化
lang: zh-CN
timezone: Asia/Shanghai

# 社交媒体
github_username: yourusername
twitter_username: yourusername

# 网站设置
show_downloads: true
google_analytics: # 如果有GA跟踪代码可以填写

# Just the Docs 主题配置
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# 导航设置
aux_links:
  "GitHub仓库":
    - "https://github.com/yourusername/awesome-sites"
  "贡献指南":
    - "/CONTRIBUTING.html"

# 页脚设置
footer_content: "Copyright &copy; 2025 Awesome Sites. 本项目采用 MIT 许可证."

# 主题定制
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  new:
    title: 新增
    color: green
  note:
    title: 注意
    color: purple
  warning:
    title: 警告
    color: red
